services:
  backend:
    build:
      context: .
    environment:
      DB_URL: jdbc:postgresql://eventhub-database:5432/eventhub
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    ports:
      - "9092:8080"

  db:
    container_name: eventhub-database
    image: docker.io/bitnami/postgresql:17.6.0-debian-12-r0
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: eventhub
    ports:
      - "5432:5432"
    volumes:
      - eventhub-postgres:/var/lib/postgresql/data

volumes:
  eventhub-postgres: