# values for bitnami postgresql chart https://artifacthub.io/packages/helm/bitnami/postgresql

architecture: "standalone"

auth:
  # this value must be set up in ci
  postgresPassword: "newPostgresPassword123"

  user: "user"
  # this value must be set up in ci
  password: "newUserPassword123"
  database: "eventhub"

shmVolume:
  enabled: true
  sizeLimit: 1Gi

primary:
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  
  networkPolicy:
    enabled: false

  persistence:
    size: 8Gi





  
