eventhubBackendDeploy:
  replicas: 1

  container:
    image:
      repository: ghcr.io/true-business/eventhub-backend
      # this value should be set on deploy
      tag: main-f0951d6
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    securityContext:
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: false
      runAsNonRoot: false
      runAsUser: 1000

  appConfig:
    mail:
      login: "events.hub@mail.ru"
      # This values must be set up in ci.
      password: "0000"
    registration:
      cleanupJob:
        cron: "0 0 0 * * *"
        zone: "Europe/Moscow"
      tokenExpirationMinutes: 5
    minio:
      # This values must be set up in ci
      user: "miniouser"
      password: "miniopassword"
      hostPort: "example-minio.com:9000"
      bucket: "eventhub"

  service:
    type: LoadBalancer
    port: 8080
  
  ingress:
    className: nginx
    host: eventhub-backend.ru
    paths:
      - path: "/some(/|$)(.*)"
        pathType: ImplementationSpecific
    tls: []

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
# livenessProbe:
#   httpGet:
#     path: "/actuator/health/liveness"
#     port: http
readinessProbe:
  httpGet:
    path: "/actuator/health/readiness"
    port: http
