eventhubBackendDeploy:
  replicas: 1

  container:
    image:
      repository: ghcr.io/true-business/eventhub-backend
      tag: $CI_IMAGE_TAG
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    securityContext:
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: false
      runAsUser: 1000

  service:
    type: ClusterIP
    port: 80
  
  ingress:
    className: "eventhub-backend"
    host: eventhub.backend
    paths:
      - path: "/api"
        pathType: Prefix
    tls: []

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  httpGet:
    path: /healthz
    port: http
readinessProbe:
  httpGet:
    path: /readyz
    port: http
