eventhubBackendDeploy:
  replicas: 1

  container:
    image:
      repository: ghcr.io/true-business/eventhub-backend
      tag: main-f0951d6
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    securityContext:
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: false
      runAsNonRoot: false
      runAsUser: 1000

  service:
    type: ClusterIP
    port: 8080
  
  ingress:
    className: "eventhub-backend"
    host: eventhub.backend
    paths:
      - path: "/api"
        pathType: Prefix
    tls: []

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
# livenessProbe:
#   httpGet:
#     path: "/actuator/health/liveness"
#     port: http
readinessProbe:
  httpGet:
    path: "/actuator/health/readiness"
    port: http
