name: "Build and push docker image"

on:
    push:
        branches:
            - "**"
        tags:
            - "v*"

jobs:
    build-and-push-docker:
       runs-on: ubuntu-latest
       permissions:
            contents: read
            packages: write
       steps:

        - name: Checkout
          uses: actions/checkout@v4

        - name: Prepare docker meta
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: |
                ghcr.io/True-Business/eventhub-backend
            tags: |
                type=ref,event=tag,priority=200
                type=sha,prefix={{branch}}-,priority=100,enable=${{ github.ref_type == 'branch' }}

        - name: Login to GHCR
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
    
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Build and push
          id: dockerbuild
          uses: docker/build-push-action@v6
          with:
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}

        - name: Save image name to file
          run: echo ${{ fromJson(steps.dockerbuild.outputs.metadata)['image.name'] }} > image-name.txt

        - name: Upload tags artifact
          uses: actions/upload-artifact@v4
          with:
            name: image-name
            path: image-name.txt
                

            

