name: "Build and push docker image"

on:
    push:
        branches:
            - "**"
        tags:
            - "v*"

jobs:
    build-and-push-docker:
       runs-on: ubuntu-latest
       steps:

        - name: Checkout
          uses: actions/checkout@v4

        - name: Prepare docker meta
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: |
                ghcr.io/True-Business/eventhub-backend
            tags: |
                type=ref,event=tag
                type=sha,prefix={{branch}}-

        - name: Login to GHCR
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
    
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}

        - name: Save tags to file
          run: echo ${{ steps.meta.outputs.tags }} > tags.txt

        - name: Upload tags artifact
          uses: actions/upload-artifact@v4
          with:
            name: image-tags
            path: tags.txt
                

            

