name: "Deploy to dev"

on: workflow_dispatch

jobs:
    build-docker-image-for-dev:
        permissions:
            contents: read
            packages: write
        uses: ./.github/workflows/build-and-push-docker-image.yml 

    deploy-to-dev:
        needs: build-docker-image-for-dev
        uses: ./.github/workflows/deploy.yml
        with:
            target-namespace: ${{ vars.DEV_NAMESPACE }}
            ingress-path: "/dev"
        secrets:
            kubeconfig: ${{ secrets.KUBECONFIG }}
            postgresPassword: ${{ secrets.DEV_POSTGRES_PASSWORD }}
            userPassword: ${{ secrets.DEV_USER_PASSWORD }}
            mailPassword: ${{ secrets.MAIL_APPLICATION_PASSWORD }}
            minioUser: ${{ secrets.MINIO_USER }}
            minioPassword: ${{ secrets.MINIO_PASSWORD }}
            minioHostPort: ${{ secrets.MINIO_HOST_PORT }}
            minioBucket: ${{ secrets.DEV_MINIO_BUCKET }}
            
    